### ISSUE TITLE
xantech.restore error nonetype object

### ISSUE THREAD

**Issue by garageboxnv** [rsnodgrass/hass-xantech#8]
@rsnodgrass I updated to 0.0.9 remotely, I get following error in home-assistant.log
`Invalid key 'zone_status_skip' in dictionary 'xantech8'; returning None`

Testing of the xantech.mute functionality was fine
Testing of the xantech.snapshot functionality was fine
Testing of the xantech.restore functionality resulted in an error

`websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/home/homeassistant/.homeassistant/custom_components/xantech/media_player.py", line 167, in async_service_call_dispatcher
    await entity.async_restore()
  File "/home/homeassistant/.homeassistant/custom_components/xantech/media_player.py", line 378, in async_restore
    await self._amp.restore_zone(self._status_snapshot)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyxantech/__init__.py", line 408, in wrapper
    return (await coro(*args, **kwargs))
  File "/srv/homeassistant/lib/python3.9/site-packages/pyxantech/__init__.py", line 498, in restore_zone
    for command in restore_commands:
TypeError: 'NoneType' object is not iterable`

Thx for fixing

_Originally posted by @garageboxnv in https://github.com/rsnodgrass/hass-xantech/issues/4#issuecomment-1207879288_

**Comment by rsnodgrass** [comment]
You have a warning (first line) that is not an issue (and removed in future versions).

What kind of amp are you using?  I see in the code this means that your amp does not support the 'restore_zone' command. This may be fine, or it may mean restore will never work. I change this to an INFO log so at least it won't emit this error.

**Comment by garageboxnv** [comment]
I have a MRAUDIO8X8, when I looked at the code I thought the library takes care of restoring the state, by executing all the commands listed in the config file:
`restore_zone:    [ 'set_power', 'set_source', 'set_volume', 'set_mute', 'set_bass', 'set_balance', 'set_treble' ]`
However it seems to me that the restore command is not set
For reference my home assistant config
`  - platform: xantech
    type: xantech8
    port: socket://desp-audio.del:9999/
    zones:
      1:
        name: "zone1"
      2:
        name: "zone2"
      3:
        name: "zone3"
      4:
        name: "zone4"
      5:
        name: "zone5"
      6:
        name: "zone6"
      7:
        name: "zone7"
      8:
        name: "zone8"
    sources:
      1:
        name: "sonos"
`

**Comment by rsnodgrass** [comment]
Interesting, restore_zone is in the protocols file for the xantech8...but it is under "extras". That is why it is not being found...it needs to look extras up first.

**Comment by rsnodgrass** [comment]
0.6.12 has the change to load restore details from the extras: section of the protocol
